apiVersion: v1
kind: Service
metadata:
  name: chatbot-wsp-service
  namespace: default
spec:
  selector:
    app: chatbot-wsp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-wsp-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chatbot-wsp
  template:
    metadata:
      labels:
        app: chatbot-wsp
    spec:
      containers:
      - name: chatbot-wsp
        image: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/chatbot-wsp:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: HOST
          value: "0.0.0.0"
        - name: LOG_LEVEL
          value: "info"
        - name: WHATSAPP_VERIFY_TOKEN
          valueFrom:
            secretKeyRef:
              name: whatsapp-secrets
              key: verify-token
        - name: WHATSAPP_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: whatsapp-secrets
              key: access-token
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
